name: Build

on:
  push:
    # Sequence of patterns matched against refs/tags
    branches-ignore:
      - master # Only check feature branches

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build docker
        run: docker build -t openra-build .

      - name: Build CA
        run: docker run -e RELEASE_VERSION=${GITHUB_SHA} -v $GITHUB_WORKSPACE:/workdir --rm openra-build ./build-docker.sh
